# appspec.yml for use with AWS CodeDeploy.
version: 0.0
os: linux
files:
  - source: /
    destination: /opt/puppet/
  - source: /extras/upstart/puppet.conf
    destination: /etc/init/
  - source: /extras/nginx/puppet
    destination: /etc/nginx/sites-available/
permissions:
  - object: /opt/puppet/
    pattern: "**"
    owner: www-data
    group: www-data
    type:
      - directory
      - file
  - object: /opt/puppet/extras/
    pattern: "*.sh"
    mode: 744
  - object: /etc/init/puppet.conf
    owner: root
    group: root
  - object: /etc/nginx/sites-available/puppet
    owner: root
    group: root
hooks:
  ApplicationStop:
    - location: extras/hooks/application-stop.sh
      timeout: 180
  BeforeInstall:
    - location: extras/hooks/before-install.sh
      timeout: 600
  AfterInstall:
    - location: extras/hooks/after-install.sh
      timeout: 600
  ApplicationStart:
    - location: extras/hooks/application-start.sh
      timeout: 180